name: MiniTest
on: [push, pull_request]
jobs:
  minitest:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
        gemfile:
          - rails_7_0
          - rails_7_1
          - rails_7_2
          - rails_8_0
          - rails_next
        image_processor:
          - vips
          - mini_magick
        exclude:
          - ruby: '3.1'
            gemfile: rails_8_0
          - gemfile: rails_6_1_4
        include:
          - ruby: '3.0'
            gemfile: rails_6_1_4
            image_processor: vips
          - ruby: '3.0'
            gemfile: rails_6_1_4
            image_processor: mini_magick
    runs-on: ubuntu-latest
    steps:
      - name: Install libvips
        run: sudo apt-get update && sudo apt-get -y install libvips

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set BUNDLE_GEMFILE
        run: echo 'BUNDLE_GEMFILE=${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile' >> $GITHUB_ENV

      - name: Set IMAGE_PROCESSOR
        run: echo 'IMAGE_PROCESSOR=${{ matrix.image_processor }}' >> $GITHUB_ENV

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
